version : '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules #It says donot try to map a folder up against app node modules inside the container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules #It says donot try to map a folder up against app node modules inside the container
      - .:/app
    command: ["npm", "run", "test"]